connect 'C:\DB\MUSICLIBRARY.FDB' user 'SYSDBA' password 'masterkey';
insert into TRACK (TRACK_ID, TRACK_NAME, TRACK_TIME,TRACK_GENRE, TRACK_YEAR, TRACK_RATING)
values (1, 'Smoke on the water', '00:04:42','Classic', '2000', 10);
insert into TRACK (TRACK_ID, TRACK_NAME, TRACK_TIME,TRACK_GENRE, TRACK_YEAR, TRACK_RATING)
values (0, 'Smoke on the water', '00:06:42','Rock', '1972', 10);
insert into TRACK (TRACK_ID, TRACK_NAME, TRACK_TIME,TRACK_GENRE, TRACK_YEAR, TRACK_RATING)
values (2, 'When a blind man cries', '00:07:12','Rock', '1972', 10);
insert into TRACK (TRACK_ID, TRACK_NAME, TRACK_TIME,TRACK_GENRE, TRACK_YEAR, TRACK_RATING)
values (3, 'Never before', '00:05:31','Rock', '1972', 9);
insert into TRACK (TRACK_ID, TRACK_NAME, TRACK_TIME,TRACK_GENRE, TRACK_YEAR, TRACK_RATING)
values (4, 'Highway star', '00:07:11','Rock', '1972', 10);
insert into TRACK (TRACK_ID, TRACK_NAME, TRACK_TIME,TRACK_GENRE, TRACK_YEAR, TRACK_RATING)
values (5, 'Fools', '00:08:08','Rock', '1970', 9);

insert into TRACK (TRACK_ID, TRACK_NAME, TRACK_TIME,TRACK_GENRE, TRACK_YEAR, TRACK_RATING)
values (6, 'Pictures of home', '00:08:42','Rock', '1972', 10);
insert into TRACK (TRACK_ID, TRACK_NAME, TRACK_TIME,TRACK_GENRE, TRACK_YEAR, TRACK_RATING)
values (7, 'Space Trucking', '00:05:12','Rock', '1972', 9);
insert into TRACK (TRACK_ID, TRACK_NAME, TRACK_TIME,TRACK_GENRE, TRACK_YEAR, TRACK_RATING)
values (8, 'Hard lovin man', '00:09:31','Rock', '1970', 8);
insert into TRACK (TRACK_ID, TRACK_NAME, TRACK_TIME,TRACK_GENRE, TRACK_YEAR, TRACK_RATING)
values (9, 'No one came', '00:06:11','Rock', '1970', 10);
insert into TRACK (TRACK_ID, TRACK_NAME, TRACK_TIME,TRACK_GENRE, TRACK_YEAR, TRACK_RATING)
values (10, 'Speed King', '00:04:25','Rock', '1970', 10);

insert into TRACK (TRACK_ID, TRACK_NAME, TRACK_TIME,TRACK_GENRE, TRACK_YEAR, TRACK_RATING)
values (11, 'Burn', '00:06:06','Rock', '1974', 10);
insert into TRACK (TRACK_ID, TRACK_NAME, TRACK_TIME,TRACK_GENRE, TRACK_YEAR, TRACK_RATING)
values (12, 'Sail Away', '00:05:52','Rock', '1974', 9);
insert into TRACK (TRACK_ID, TRACK_NAME, TRACK_TIME,TRACK_GENRE, TRACK_YEAR, TRACK_RATING)
values (13, 'You Fool No One', '00:04:48','Rock', '1974', 7);
insert into TRACK (TRACK_ID, TRACK_NAME, TRACK_TIME,TRACK_GENRE, TRACK_YEAR, TRACK_RATING)
values (14, 'Mistreated', '00:07:30','Rock', '1974', 10);
insert into TRACK (TRACK_ID, TRACK_NAME, TRACK_TIME,TRACK_GENRE, TRACK_YEAR, TRACK_RATING)
values (15, 'A200', '00:04:05','Rock', '1974', 5);

INSERT INTO TRACK (TRACK_ID,TRACK_NAME,TRACK_TIME,TRACK_GENRE,TRACK_YEAR,TRACK_RATING) VALUES (16,'DQQLLGlMP_oLSM_','00:55:21','Hard Rock',1995,10);
INSERT INTO TRACK (TRACK_ID,TRACK_NAME,TRACK_TIME,TRACK_GENRE,TRACK_YEAR,TRACK_RATING) VALUES (17,'Kuhjve','00:47:51','Rock',2014,10);
INSERT INTO TRACK (TRACK_ID,TRACK_NAME,TRACK_TIME,TRACK_GENRE,TRACK_YEAR,TRACK_RATING) VALUES (18,'^bxTG','00:54:31','Blues',2011,4);
INSERT INTO TRACK (TRACK_ID,TRACK_NAME,TRACK_TIME,TRACK_GENRE,TRACK_YEAR,TRACK_RATING) VALUES (19,'RMVe\ZCCwg[btz','00:42:11','Rock',1960,5);
INSERT INTO TRACK (TRACK_ID,TRACK_NAME,TRACK_TIME,TRACK_GENRE,TRACK_YEAR,TRACK_RATING) VALUES (20,'BgE`uGaf','00:52:11','Rock',1998,7);
INSERT INTO TRACK (TRACK_ID,TRACK_NAME,TRACK_TIME,TRACK_GENRE,TRACK_YEAR,TRACK_RATING) VALUES (21,'Lmfw]','00:45:21','Hard Rock',1963,3);
INSERT INTO TRACK (TRACK_ID,TRACK_NAME,TRACK_TIME,TRACK_GENRE,TRACK_YEAR,TRACK_RATING) VALUES (22,'TCniK','00:52:11','Rock',1959,5);
INSERT INTO TRACK (TRACK_ID,TRACK_NAME,TRACK_TIME,TRACK_GENRE,TRACK_YEAR,TRACK_RATING) VALUES (23,']vHZwoPrIIowMM','00:52:11','Classic',1961,3);
INSERT INTO TRACK (TRACK_ID,TRACK_NAME,TRACK_TIME,TRACK_GENRE,TRACK_YEAR,TRACK_RATING) VALUES (24,'VmMQXGWc','00:56:41','Blues',1961,3);
INSERT INTO TRACK (TRACK_ID,TRACK_NAME,TRACK_TIME,TRACK_GENRE,TRACK_YEAR,TRACK_RATING) VALUES (25,'[]WdBo','00:55:21','Hard Rock',1955,9);
INSERT INTO TRACK (TRACK_ID,TRACK_NAME,TRACK_TIME,TRACK_GENRE,TRACK_YEAR,TRACK_RATING) VALUES (26,'bMmEIHEWRBI','00:45:21','Hard Rock',1986,5);
INSERT INTO TRACK (TRACK_ID,TRACK_NAME,TRACK_TIME,TRACK_GENRE,TRACK_YEAR,TRACK_RATING) VALUES (27,'hXavuNw\vTQY','00:45:21','Classic',1965,6);
INSERT INTO TRACK (TRACK_ID,TRACK_NAME,TRACK_TIME,TRACK_GENRE,TRACK_YEAR,TRACK_RATING) VALUES (28,'wDLgbuAoO','00:44:31','Classic',1968,10);
INSERT INTO TRACK (TRACK_ID,TRACK_NAME,TRACK_TIME,TRACK_GENRE,TRACK_YEAR,TRACK_RATING) VALUES (29,'rgbwScFd^yN','00:47:51','Classic',1972,4);
INSERT INTO TRACK (TRACK_ID,TRACK_NAME,TRACK_TIME,TRACK_GENRE,TRACK_YEAR,TRACK_RATING) VALUES (30,'uZBLVWVk`','00:44:31','Hard Rock',1951,4);
INSERT INTO TRACK (TRACK_ID,TRACK_NAME,TRACK_TIME,TRACK_GENRE,TRACK_YEAR,TRACK_RATING) VALUES (31,'OnsUQWDvzEg','00:57:51','Hard Rock',1976,7);
INSERT INTO TRACK (TRACK_ID,TRACK_NAME,TRACK_TIME,TRACK_GENRE,TRACK_YEAR,TRACK_RATING) VALUES (32,'iH`VCkjyCwXGQ','00:45:21','Blues',1979,7);
INSERT INTO TRACK (TRACK_ID,TRACK_NAME,TRACK_TIME,TRACK_GENRE,TRACK_YEAR,TRACK_RATING) VALUES (33,'G[OYJu^F','00:52:11','Rock',1961,4);
INSERT INTO TRACK (TRACK_ID,TRACK_NAME,TRACK_TIME,TRACK_GENRE,TRACK_YEAR,TRACK_RATING) VALUES (34,'YHwIVXhh','00:56:41','Classic',1960,3);
INSERT INTO TRACK (TRACK_ID,TRACK_NAME,TRACK_TIME,TRACK_GENRE,TRACK_YEAR,TRACK_RATING) VALUES (35,'rkvmIT[MFCvvqeC','00:44:31','Blues',2015,10);
INSERT INTO TRACK (TRACK_ID,TRACK_NAME,TRACK_TIME,TRACK_GENRE,TRACK_YEAR,TRACK_RATING) VALUES (36,'\zGNX^uq','00:55:21','Rock',2005,5);
INSERT INTO TRACK (TRACK_ID,TRACK_NAME,TRACK_TIME,TRACK_GENRE,TRACK_YEAR,TRACK_RATING) VALUES (37,'moVVcRZTiugrqgV','00:40:01','Rock',1969,6);
INSERT INTO TRACK (TRACK_ID,TRACK_NAME,TRACK_TIME,TRACK_GENRE,TRACK_YEAR,TRACK_RATING) VALUES (38,'OTTQFVAuET]AaUu','00:44:31','Classic',1985,7);
INSERT INTO TRACK (TRACK_ID,TRACK_NAME,TRACK_TIME,TRACK_GENRE,TRACK_YEAR,TRACK_RATING) VALUES (39,'OwJDFKrYI','00:47:51','Classic',2012,5);
INSERT INTO TRACK (TRACK_ID,TRACK_NAME,TRACK_TIME,TRACK_GENRE,TRACK_YEAR,TRACK_RATING) VALUES (40,'eGrQpvA','00:47:51','Classic',1997,9);
INSERT INTO TRACK (TRACK_ID,TRACK_NAME,TRACK_TIME,TRACK_GENRE,TRACK_YEAR,TRACK_RATING) VALUES (41,'ozed``DG','00:44:31','Classic',2014,9);
INSERT INTO TRACK (TRACK_ID,TRACK_NAME,TRACK_TIME,TRACK_GENRE,TRACK_YEAR,TRACK_RATING) VALUES (42,'PVU]uWkd','00:46:41','Classic',1957,7);
INSERT INTO TRACK (TRACK_ID,TRACK_NAME,TRACK_TIME,TRACK_GENRE,TRACK_YEAR,TRACK_RATING) VALUES (43,'ZQUOCHVr_ZxyvpI','00:55:21','Hard Rock',2012,10);
INSERT INTO TRACK (TRACK_ID,TRACK_NAME,TRACK_TIME,TRACK_GENRE,TRACK_YEAR,TRACK_RATING) VALUES (44,'L][[dQ','00:56:41','Classic',1986,7);
INSERT INTO TRACK (TRACK_ID,TRACK_NAME,TRACK_TIME,TRACK_GENRE,TRACK_YEAR,TRACK_RATING) VALUES (45,'RxlpIuEjSv]xm','00:52:11','Classic',1970,5);
INSERT INTO TRACK (TRACK_ID,TRACK_NAME,TRACK_TIME,TRACK_GENRE,TRACK_YEAR,TRACK_RATING) VALUES (46,'inbvQpWgrgl]mV','00:50:01','Hard Rock',2009,8);
INSERT INTO TRACK (TRACK_ID,TRACK_NAME,TRACK_TIME,TRACK_GENRE,TRACK_YEAR,TRACK_RATING) VALUES (47,'wJn[HjNs','00:54:31','Hard Rock',1991,3);
INSERT INTO TRACK (TRACK_ID,TRACK_NAME,TRACK_TIME,TRACK_GENRE,TRACK_YEAR,TRACK_RATING) VALUES (48,'YSXnXh','00:42:11','Blues',2008,8);
INSERT INTO TRACK (TRACK_ID,TRACK_NAME,TRACK_TIME,TRACK_GENRE,TRACK_YEAR,TRACK_RATING) VALUES (49,'cthktQX','00:52:11','Classic',1962,5);
INSERT INTO TRACK (TRACK_ID,TRACK_NAME,TRACK_TIME,TRACK_GENRE,TRACK_YEAR,TRACK_RATING) VALUES (50,'LcEIc`kFPW','00:46:41','Blues',2015,4);
INSERT INTO TRACK (TRACK_ID,TRACK_NAME,TRACK_TIME,TRACK_GENRE,TRACK_YEAR,TRACK_RATING) VALUES (51,'GdXO`\^Nh`[nPSg','00:47:51','Blues',2003,4);
INSERT INTO TRACK (TRACK_ID,TRACK_NAME,TRACK_TIME,TRACK_GENRE,TRACK_YEAR,TRACK_RATING) VALUES (52,'UiLelxwuj','00:45:21','Blues',1981,4);
INSERT INTO TRACK (TRACK_ID,TRACK_NAME,TRACK_TIME,TRACK_GENRE,TRACK_YEAR,TRACK_RATING) VALUES (53,'vqFNXxorz^','00:46:41','Hard Rock',2010,4);
INSERT INTO TRACK (TRACK_ID,TRACK_NAME,TRACK_TIME,TRACK_GENRE,TRACK_YEAR,TRACK_RATING) VALUES (54,'ZueHfJeAxWwuE`m','00:50:01','Rock',1978,6);
INSERT INTO TRACK (TRACK_ID,TRACK_NAME,TRACK_TIME,TRACK_GENRE,TRACK_YEAR,TRACK_RATING) VALUES (55,'WhEf[\X','00:54:31','Hard Rock',1951,3);
INSERT INTO TRACK (TRACK_ID,TRACK_NAME,TRACK_TIME,TRACK_GENRE,TRACK_YEAR,TRACK_RATING) VALUES (56,'LrozwVX^QFc','00:47:51','Rock',1993,5);
INSERT INTO TRACK (TRACK_ID,TRACK_NAME,TRACK_TIME,TRACK_GENRE,TRACK_YEAR,TRACK_RATING) VALUES (57,'b]\LxgIW','00:55:21','Classic',1975,7);
INSERT INTO TRACK (TRACK_ID,TRACK_NAME,TRACK_TIME,TRACK_GENRE,TRACK_YEAR,TRACK_RATING) VALUES (58,'prUua_VaDu','00:40:01','Rock',1978,7);
INSERT INTO TRACK (TRACK_ID,TRACK_NAME,TRACK_TIME,TRACK_GENRE,TRACK_YEAR,TRACK_RATING) VALUES (59,'spNZAIQFWyE','00:46:41','Rock',2000,6);
INSERT INTO TRACK (TRACK_ID,TRACK_NAME,TRACK_TIME,TRACK_GENRE,TRACK_YEAR,TRACK_RATING) VALUES (60,'qvXSGGzauj\uslc','00:52:11','Hard Rock',1965,8);
INSERT INTO TRACK (TRACK_ID,TRACK_NAME,TRACK_TIME,TRACK_GENRE,TRACK_YEAR,TRACK_RATING) VALUES (61,'yz]vaZEe','00:40:01','Blues',1988,3);
INSERT INTO TRACK (TRACK_ID,TRACK_NAME,TRACK_TIME,TRACK_GENRE,TRACK_YEAR,TRACK_RATING) VALUES (62,'h\_DCwmtEiPI\','00:40:01','Rock',1973,10);
INSERT INTO TRACK (TRACK_ID,TRACK_NAME,TRACK_TIME,TRACK_GENRE,TRACK_YEAR,TRACK_RATING) VALUES (63,'ioEZaqNiioTz','00:47:51','Hard Rock',1967,7);
INSERT INTO TRACK (TRACK_ID,TRACK_NAME,TRACK_TIME,TRACK_GENRE,TRACK_YEAR,TRACK_RATING) VALUES (64,'i\lEpJb','00:44:31','Classic',2015,6);
INSERT INTO TRACK (TRACK_ID,TRACK_NAME,TRACK_TIME,TRACK_GENRE,TRACK_YEAR,TRACK_RATING) VALUES (65,'tfkkaBApAko','00:46:41','Classic',2014,10);
COMMIT;
